# [7] Numpy 종합 실습

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

- **데이터 (**각 지점의 월별 과일 판매량(단위: 개))

    ```python
    import numpy as np

    # 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
    # 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
    sales_data = np.array([
        # 지점 1
        [[120, 150, 200, 230, 180, 210],  # 사과 판매량
         [100, 140, 170, 190, 160, 180],  # 바나나 판매량
         [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

        # 지점 2
        [[80, 90, 110, 140, 130, 120],
         [60, 70, 90, 100, 110, 95],
         [50, 80, 100, 110, 90, 85]],

        # 지점 3
        [[130, 140, 160, 180, 170, 190],
         [110, 120, 130, 150, 140, 160],
         [100, 110, 120, 130, 120, 140]],

        # 지점 4
        [[100, 130, 150, 170, 160, 180],
         [90, 100, 110, 120, 130, 125],
         [80, 110, 140, 130, 120, 110]],

        # 지점 5
        [[90, 110, 130, 140, 120, 130],
         [70, 85, 100, 110, 105, 95],
         [60, 90, 110, 100, 90, 95]]
    ])
    fruits = np.array(["사과", "바나나", "오렌지"])
    branches = np.array(["지점1", "지점2", "지점3", "지점4", "지점5"])
    months = np.array(["1월", "2월", "3월", "4월", "5월", "6월"])




    ```

In [1]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

fruits = np.array(["사과", "바나나", "오렌지"])
branches = np.array(["지점1", "지점2", "지점3", "지점4", "지점5"])
months = np.array(["1월", "2월", "3월", "4월", "5월", "6월"])

In [2]:
# 1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 평균 판매량을 계산하세요.
branch_avgs = np.mean(sales_data, axis=2) # 각 지점 과일별 판매 평균
# print(branch_avgs)

print("각 지점 과일 6개월 판매 평균")
for b_index, b_name in enumerate(branches):
    print(f'[{b_name}]')
    for f_index, f_name in enumerate(fruits):
        print(f"{f_name} : {branch_avgs[b_index, f_index]:.2f}") #.2f = 소수점 아래 둘째 자리까지

각 지점 과일 6개월 판매 평균
[지점1]
사과 : 181.67
바나나 : 156.67
오렌지 : 131.67
[지점2]
사과 : 111.67
바나나 : 87.50
오렌지 : 85.83
[지점3]
사과 : 161.67
바나나 : 135.00
오렌지 : 120.00
[지점4]
사과 : 148.33
바나나 : 112.50
오렌지 : 115.00
[지점5]
사과 : 120.00
바나나 : 94.17
오렌지 : 90.83


In [3]:
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
monthly_fruits_total = np.sum(sales_data, axis=0) # 전체 지점 각 월마다 과일별 합계
print(sales_data.shape)
# print(monthly_fruits_total)
#  [[520 620 750 860 760 830] # 사과: 1월-520개, 2월-620개 ...
#  [430 515 600 670 645 655]  # 바나나: 1월-420개, 2월-515개...
#  [380 510 630 610 550 580]] # 오렌지: 1월-380개, 2월-510개

bested_fruits = np.argmax(monthly_fruits_total, axis=0)
# 각 지점 월마다 과일별 합계 중 최대값 인덱스 반환(argmax)
#print(bested_fruits)
# [0 0 0 0 0 0] # 모든 월마다 사과가 제일 많이 팔림
print("각 월마다 전체 지점에서 가장 많이 판매된 과일명/판매량")
for m_index, m_name in enumerate(months):
    fruits_index = bested_fruits[m_index] # 각 월마다 가장 많이 팔린 과일의 인덱스 찾기
    fruits_name = fruits[fruits_index] # 과일 인덱스를 이용해 과일명 list에서 과일명 찾기
    sales_amount = monthly_fruits_total[fruits_index, m_index] # [과일명 인덱스, 월 인덱스] -> 해당 과일 판매량 합계
    print(f"{m_name} : {fruits_name} / {sales_amount}")

(5, 3, 6)
각 월마다 전체 지점에서 가장 많이 판매된 과일명/판매량
1월 : 사과 / 520
2월 : 사과 / 620
3월 : 사과 / 750
4월 : 사과 / 860
5월 : 사과 / 760
6월 : 사과 / 830


In [4]:
# 3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
fruits_sales_total = np.sum(monthly_fruits_total, axis=1) # 전체 지점 각 월마다 과일별 합계에서 과일별 판매량 합
#print(fruits_sales_total) # [4340 3515 3260]
# for f_index, f_name in enumerate(fruits):
#     print(f"{f_name} : {fruits_sales_total[f_index]}")
print("가장 많이 판매된 과일: ", fruits[np.argmax(fruits_sales_total)])
print("판매량: ", fruits_sales_total[np.argmax(fruits_sales_total)])

가장 많이 판매된 과일:  사과
판매량:  4340


In [5]:
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
print("각 지점에서 판매량이 150개 이상인 지점, 과일")

for b_index, b_name in enumerate(branches):

    selected_fruits_names = []

    for f_index, f_name in enumerate(fruits):
        fruits_sales = sales_data[b_index, f_index]
        if np.max(fruits_sales) >= 150:
            selected_fruits_names.append(f_name)

    if selected_fruits_names:
        print(f"[{b_name}]")
        print(", ".join(selected_fruits_names))

각 지점에서 판매량이 150개 이상인 지점, 과일
[지점1]
사과, 바나나, 오렌지
[지점3]
사과, 바나나
[지점4]
사과
